apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - jaeger.yaml
  - loki.yaml
  - prometheus.yaml
  - grafana.yaml
  - otel-collector.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: reactive-system
      app.kubernetes.io/component: observability
