apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - zookeeper.yaml
  - kafka.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: reactive-system
      app.kubernetes.io/component: messaging
