apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - drools.yaml
  - gateway.yaml
  - ui.yaml
  - ui-nginx-config.yaml
  # - benchmark.yaml  # Disabled - benchmark image needs to be built

labels:
  - pairs:
      app.kubernetes.io/part-of: reactive-system
      app.kubernetes.io/component: application
