apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces/namespaces.yaml
  - kafka/
  - flink/
  - application/
  - observability/

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: reactive-system
