apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - jobmanager.yaml
  - taskmanager.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: reactive-system
      app.kubernetes.io/component: stream-processing
